[package]
org = "PubuduGunatilaka"
name = "petmgt"
version = "1.0.0"
export = ["petmgt"]
distribution = "2201.3.1"

[build-options]
observabilityIncluded = true


[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"

[[platform.java11.dependency]]
path = "/Users/pubudugunatilaka/wso2/choreo-projects/p1/mysql-connector-java-8.0.26.jar”